POST http://127.0.0.1:8080/transcript
Content-Type: application/x-www-form-urlencoded

course=PE+1550&term=108&year=4&grade=Pass&request-insert=
###
POST http://127.0.0.1:8080/flowershop
Content-Type: application/x-www-form-urlencoded

name=2300+Cafe&phone=607-555-5555&bouquet=zinnias&request-sample=